[tool.poetry]
name = "ciffy"
version = "0.1.0"
description = ""
authors = ["Hamish M. Blair <hmblair@stanford.edu>"]
license = "CC BY-NC 4.0"
readme = "README.md"
homepage = "https://github.com/hmblair/ciffy"

[tool.poetry.dependencies]
python = "^3.11"
numpy = "^1.21.0"
torch = "^2.0.0"

[tool.poetry-dynamic-versioning]
enable = true
vcs = "git"
style = "pep440"

[tool.poetry-dynamic-versioning.substitution]
files = ["ciffy/__init__.py"]

[build-system]
requires = ["poetry-core>=1.0.0", "poetry-dynamic-versioning>=1.0.0,<2.0.0"]
build-backend = "poetry_dynamic_versioning.backend"
