[tool.poetry]
name = "ciffy"
version = "0.1.0"
description = ""
authors = ["Hamish M. Blair <hmblair@stanford.edu>"]
license = "CC BY-NC 4.0"
readme = "README.md"
homepage = "https://github.com/hmblair/ciffy"

[tool.poetry.dependencies]
python = "^3.11"
numpy = "^1.21.0"
torch = "^2.0.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
