[tool.poetry]
name = "ciffy"
version = "0.1.0"
description = ""
authors = ["Hamish M. Blair <hmblair@stanford.edu>"]
license = "CC BY-NC 4.0"
homepage = "https://github.com/hmblair/ciffy"

[tool.poetry.dependencies]
python = "^3.8"
numpy = "^1.21.0"

[tool.poetry.dev-dependencies]

[tool.poetry.build]
generate-setup-py = true

[tool.poetry.scripts]

[tool.poetry.plugins."poetry-plugin-ciffy.extensions"]
_ciffy_c = { src = "ciffy/src/_ciffy_c.c", include = ["numpy"] }

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
