"""
Biochemistry constants and enumerations.

Defines atoms, residues, elements, and nucleotide structures.

Residue members are AtomGroups with geometry:
    Residue.A.P             # Atom(P, 2) - IS an int
    Residue.A.ideal         # (n, 3) ideal coordinates
    Residue.A.bonds         # (n, 2) bond pairs
    Residue.ALA.CA          # Atom for CA in alanine
"""

import numpy as np

from ._generated_elements import Element, ELEMENT_NAMES
from ._generated_molecule import Molecule, molecule_type

# =============================================================================
# RESIDUE SYSTEM - AtomGroup-based (the main system)
# =============================================================================
from ._generated_residues_v2 import Residue, CIF_RESIDUE_NAMES
from ._generated_atoms_v2 import ATOM_NAMES

# Dihedral ownership arrays - generated by codegen
try:
    from ._generated_dihedrals import ATOM_DIHEDRAL_TYPE, ATOM_DIHEDRAL_REFS
except ImportError:
    ATOM_DIHEDRAL_TYPE = np.array([], dtype=np.int8)
    ATOM_DIHEDRAL_REFS = np.zeros((0, 3, 2), dtype=np.int8)

# DihedralType enum
from ._generated_dihedraltypes import (
    DihedralType,
    PROTEIN_BACKBONE,
    RNA_BACKBONE,
    RNA_GLYCOSIDIC,
    RNA_BACKBONE_EXTENDED,
    PROTEIN_SIDECHAIN,
    DIHEDRAL_NAME_TO_TYPE,
    DIHEDRAL_ATOMS,
)

# Hierarchical atom groups - AtomGroup-based
from .constants import (
    # Flat IndexEnums (prefixed atom names) - legacy, kept for compatibility
    Backbone,
    Nucleobase,
    Phosphate,
    Sidechain,
    # AtomGroup-based hierarchical groups (preferred)
    Sugar2 as Sugar,
    PhosphateGroup2 as PhosphateGroup,
    PurineImidazole2 as PurineImidazole,
    PurinePyrimidine2 as PurinePyrimidine,
    PurineBase2 as PurineBase,
    PyrimidineBase2 as PyrimidineBase,
)

from .linking import (
    LinkingDefinition,
    NUCLEIC_ACID_LINK,
    PEPTIDE_LINK,
    LINKING_BY_TYPE,
)

# =============================================================================
# LEGACY SYSTEM - kept for backward compatibility
# =============================================================================
from ._generated_residues import Residue as ResidueLegacy
from ._generated_residues import CIF_RESIDUE_NAMES as CIF_RESIDUE_NAMES_LEGACY
from ._generated_atoms import (
    RibonucleicAcid,
    RibonucleicAcidNoPrefix,
    DeoxyribonucleicAcid,
    ModifiedNucleotides,
    AminoAcids,
    ATOM_NAMES as ATOM_NAMES_LEGACY,
)
from .constants import (
    Sugar as SugarLegacy,
    PhosphateGroup as PhosphateGroupLegacy,
    PurineImidazole as PurineImidazoleLegacy,
    PurinePyrimidine as PurinePyrimidineLegacy,
    PurineBase as PurineBaseLegacy,
    PyrimidineBase as PyrimidineBaseLegacy,
)

# =============================================================================
# VOCABULARY SIZES (for embedding layers)
# =============================================================================

NUM_ELEMENTS: int = max(e.value for e in Element) + 1
NUM_RESIDUES: int = Residue.count()
NUM_ATOMS: int = max(ATOM_NAMES.keys()) + 1


__all__ = [
    # Vocabulary sizes
    "NUM_ELEMENTS",
    "NUM_RESIDUES",
    "NUM_ATOMS",
    # Reverse lookups
    "ATOM_NAMES",
    "ELEMENT_NAMES",
    "CIF_RESIDUE_NAMES",
    # Dihedral ownership arrays
    "ATOM_DIHEDRAL_TYPE",
    "ATOM_DIHEDRAL_REFS",
    # Elements
    "Element",
    # Residues (AtomGroup-based)
    "Residue",
    # Hierarchical atom groups (AtomGroup-based)
    "Sugar",
    "PhosphateGroup",
    "PurineImidazole",
    "PurinePyrimidine",
    "PurineBase",
    "PyrimidineBase",
    # Flat IndexEnums (legacy, kept for compatibility)
    "Backbone",
    "Nucleobase",
    "Phosphate",
    "Sidechain",
    # Legacy combined atom enums
    "RibonucleicAcid",
    "RibonucleicAcidNoPrefix",
    "DeoxyribonucleicAcid",
    "ModifiedNucleotides",
    "AminoAcids",
    # Linking
    "LinkingDefinition",
    "NUCLEIC_ACID_LINK",
    "PEPTIDE_LINK",
    "LINKING_BY_TYPE",
    # Molecule types
    "Molecule",
    "molecule_type",
    # Dihedral types
    "DihedralType",
    "PROTEIN_BACKBONE",
    "RNA_BACKBONE",
    "RNA_GLYCOSIDIC",
    "RNA_BACKBONE_EXTENDED",
    "PROTEIN_SIDECHAIN",
    "DIHEDRAL_NAME_TO_TYPE",
    "DIHEDRAL_ATOMS",
    # Legacy (for backward compatibility)
    "ResidueLegacy",
]
