"""
Biochemistry constants and enumerations.

Defines atoms, residues, elements, and nucleotide structures.

Atom enums are accessed via Residue members:
    Residue.A.C3p.value    # atom index for C3' in adenosine
    Residue.ALA.CA.value   # atom index for CA in alanine
"""

import numpy as np

from ._generated_elements import Element, ELEMENT_NAMES
from ._generated_residues import Residue, CIF_RESIDUE_NAMES
from ._generated_atoms import (
    # Combined enums (for bulk operations)
    RibonucleicAcid,
    RibonucleicAcidNoPrefix,
    DeoxyribonucleicAcid,
    ModifiedNucleotides,
    AminoAcids,
    # Reverse lookup
    ATOM_NAMES,
)

# Dihedral ownership arrays - generated by codegen
# These may not exist before first build, so provide fallback empty arrays
try:
    from ._generated_dihedrals import ATOM_DIHEDRAL_TYPE, ATOM_DIHEDRAL_REFS
except ImportError:
    # Fallback for development before codegen runs
    ATOM_DIHEDRAL_TYPE = np.array([], dtype=np.int8)
    ATOM_DIHEDRAL_REFS = np.zeros((0, 3, 2), dtype=np.int8)

# DihedralType enum - generated by codegen (IndexEnum for array methods)
from ._generated_dihedraltypes import (
    DihedralType,
    PROTEIN_BACKBONE,
    RNA_BACKBONE,
    RNA_GLYCOSIDIC,
    RNA_BACKBONE_EXTENDED,
    PROTEIN_SIDECHAIN,
    DIHEDRAL_NAME_TO_TYPE,
    DIHEDRAL_ATOMS,
)
from .constants import (
    # Flat IndexEnums (prefixed atom names)
    Backbone,
    Nucleobase,
    Phosphate,
    Sidechain,
    # Hierarchical atom groups (chemical identity)
    Sugar,
    PhosphateGroup,
    PurineImidazole,
    PurinePyrimidine,
    PurineBase,
    PyrimidineBase,
    # New AtomGroup-based hierarchical groups (v2)
    Sugar2,
    PhosphateGroup2,
    PurineImidazole2,
    PurinePyrimidine2,
    PurineBase2,
    PyrimidineBase2,
)
from .linking import (
    LinkingDefinition,
    NUCLEIC_ACID_LINK,
    PEPTIDE_LINK,
    LINKING_BY_TYPE,
)
from ._generated_molecule import Molecule, molecule_type

# =============================================================================
# NEW ATOM SYSTEM (v2) - using plain classes instead of metaclasses
# =============================================================================
# These are the new implementations that will eventually replace the legacy system.
# Import with different names during migration to avoid breaking existing code.
from ._generated_atoms_v2 import ATOM_NAMES as ATOM_NAMES_V2
from ._generated_residues_v2 import Residue as Residue2
from ._generated_residues_v2 import CIF_RESIDUE_NAMES as CIF_RESIDUE_NAMES_V2

# =============================================================================
# VOCABULARY SIZES (for embedding layers)
# =============================================================================

# Number of element types (max index + 1)
NUM_ELEMENTS: int = max(e.value for e in Element) + 1

# Number of residue types
NUM_RESIDUES: int = len(Residue)

# Number of atom types (max index + 1)
NUM_ATOMS: int = max(ATOM_NAMES.keys()) + 1


__all__ = [
    # Vocabulary sizes
    "NUM_ELEMENTS",
    "NUM_RESIDUES",
    "NUM_ATOMS",
    # Reverse lookups
    "ATOM_NAMES",
    "ELEMENT_NAMES",
    "CIF_RESIDUE_NAMES",
    # Dihedral ownership arrays
    "ATOM_DIHEDRAL_TYPE",
    "ATOM_DIHEDRAL_REFS",
    # Elements
    "Element",
    # Residues (access atoms via Residue.X.atom_name)
    "Residue",
    # Combined atom enums (for bulk operations)
    "RibonucleicAcid",
    "RibonucleicAcidNoPrefix",
    "DeoxyribonucleicAcid",
    "ModifiedNucleotides",
    "AminoAcids",
    # Atom group constants (flat IndexEnums with prefixed names)
    "Backbone",
    "Nucleobase",
    "Phosphate",
    "Sidechain",
    # Hierarchical atom groups (chemical identity, HierarchicalEnum)
    "Sugar",
    "PhosphateGroup",
    "PurineImidazole",
    "PurinePyrimidine",
    "PurineBase",
    "PyrimidineBase",
    # Linking
    "LinkingDefinition",
    "NUCLEIC_ACID_LINK",
    "PEPTIDE_LINK",
    "LINKING_BY_TYPE",
    # Molecule types
    "Molecule",
    "molecule_type",
    # Dihedral types (IndexEnum)
    "DihedralType",
    "PROTEIN_BACKBONE",
    "RNA_BACKBONE",
    "RNA_GLYCOSIDIC",
    "RNA_BACKBONE_EXTENDED",
    "PROTEIN_SIDECHAIN",
    "DIHEDRAL_NAME_TO_TYPE",
    "DIHEDRAL_ATOMS",
    # New atom system (v2) - during migration
    "Residue2",
    "ATOM_NAMES_V2",
    "CIF_RESIDUE_NAMES_V2",
    # New hierarchical groups (v2)
    "Sugar2",
    "PhosphateGroup2",
    "PurineImidazole2",
    "PurinePyrimidine2",
    "PurineBase2",
    "PyrimidineBase2",
]
